name: DevelopmentBuild

on:
  push:
    branches:
      - master
      
env:
      #リポジトリのルートディレクトリを起点としたソリューションファイルのパス
      SOLUTION_FILE_PATH:  project/DirectXgame.sln
      #Visual Studioの構成
      CONFIGURATION: Development

jobs:
  build:
    runs-on: windows-2022

    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Add MSBuild to PATH
       uses: microsoft/setup-msbuild@v2
       with:
         msbuild-architecture: x64
     - name: Build
       run: |
        msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
